language: csharp
solution: ConsoleCalculator.sln
mono: none
dotnet: 2.2.5
install:
            - dotnet restore
script:
            - dotnet build
                  - dotnet test ConsoleCalculator.Tests/ConsoleCalculator.Tests.csproj
